version: '3.8'

services:
  # --- 1. Base de Données ---
  postgres-db:
    image: postgres:15
    container_name: school_db_container
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seif
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - school-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 2. Backend Spring Boot ---
  backend-app:
    # Option A : Utiliser l'image en ligne (Recommandé pour la démo/prod)
    image: seifeddinelamti/schoolmanagement_back:latest
    
    # Option B : Construire depuis le code source local (Décommenter pour le dev)
    # build:
    #   context: ../Relead_SchoolManagement
    #   dockerfile: Dockerfile
    
    container_name: school_backend
    ports:
      - "8086:8086"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/school_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: seif
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - school-network

  # --- 3. Frontend Angular ---
  frontend-app:
    # Option A : Utiliser l'image en ligne
    image: seifeddinelamti/schoolmanagement_front:latest
    
    # Option B : Construire depuis le code source local (Décommenter pour le dev)
    # build:
    #   context: ../relead-school-front
    #   dockerfile: Dockerfile
    
    container_name: school_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend-app
    networks:
      - school-network

volumes:
  pg_data:

networks:
  school-network:
    driver: bridge